sudo: required
language: generic

services:
  - docker


before_install:
  - docker build -t hgowda/docker-test -f Dockerfile.dev .


script:
  - docker run -e CI=true hgowda/docker-test npm run test -- --coverage